
import "./globals.css";
import NavBar from "./components/NavBar";
import { ReactNode } from "react";
import { Metadata } from "next";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="h-screen">
          <NavBar />
          <main className="mt-8 mx-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
